from pathlib import Path

from docx import Document
from docx.enum.text import WD_ALIGN_PARAGRAPH
from docx.shared import Inches, Pt

from src.models.requirements import RequirementState


class SRDGenerator:
    """Create a readable Software Requirements Document from structured state."""

    def generate(self, state: RequirementState, output_path: Path) -> Path:
        document = Document()
        section = document.sections[0]
        section.top_margin = Inches(0.75)
        section.bottom_margin = Inches(0.75)
        section.left_margin = Inches(0.85)
        section.right_margin = Inches(0.85)

        normal = document.styles["Normal"]
        normal.font.name = "Aptos"
        normal.font.size = Pt(10)

        title = document.add_paragraph()
        title.alignment = WD_ALIGN_PARAGRAPH.CENTER
        title.add_run("Software Requirements Document").bold = True
        title.runs[0].font.size = Pt(26)
        subtitle = document.add_paragraph()
        subtitle.alignment = WD_ALIGN_PARAGRAPH.CENTER
        subtitle.add_run("AI Requirements Wizard").italic = True
        document.add_paragraph()

        self._heading(document, "1. Executive Summary")
        document.add_paragraph(state.business_objective or "No business objective was provided.")
        self._heading(document, "2. Requirements Overview")
        self._requirement_table(document, "Functional Requirements", state.functional_requirements, "FR")
        self._requirement_table(document, "Non-Functional Requirements", state.non_functional_requirements, "NFR")
        self._list_section(document, "3. User Roles", state.user_roles)
        self._list_section(document, "4. Constraints and Risks", state.constraints + state.risks)
        self._list_section(document, "5. Assumptions", state.assumptions)
        self._list_section(document, "6. Open Issues", state.open_questions)

        footer = section.footer.paragraphs[0]
        footer.alignment = WD_ALIGN_PARAGRAPH.CENTER
        footer.add_run("Generated by AI Requirements Wizard")
        output_path.parent.mkdir(parents=True, exist_ok=True)
        document.core_properties.title = "Software Requirements Document"
        document.core_properties.subject = "Structured software requirements"
        document.save(output_path)
        return output_path

    @staticmethod
    def _heading(document: Document, text: str) -> None:
        document.add_heading(text, level=1)

    @staticmethod
    def _requirement_table(document: Document, title: str, values: list[str], prefix: str) -> None:
        document.add_heading(title, level=2)
        if not values:
            document.add_paragraph("No information captured.")
            return
        table = document.add_table(rows=1, cols=2)
        table.style = "Light Shading Accent 1"
        table.rows[0].cells[0].text = "ID"
        table.rows[0].cells[1].text = "Requirement"
        for index, value in enumerate(values, 1):
            cells = table.add_row().cells
            cells[0].text = f"{prefix}-{index:03d}"
            cells[1].text = value

    @staticmethod
    def _list_section(document: Document, title: str, values: list[str]) -> None:
        document.add_heading(title, level=1)
        if not values:
            document.add_paragraph("No information captured.")
            return
        for value in values:
            document.add_paragraph(value, style="List Bullet")
